#!/bin/bash

# This script generates the static HTML website from the source files in
# the snapshot being committed.  The results are committed to the `static`
# branch.

set -e

if [ "$(git symbolic-ref HEAD)" == "refs/heads/master" ]; then
  TEMP_DIR=$(mktemp -d)
  PELICAN=$HOME/.virtualenvs/pelican/bin/pelican
  GHPIMPORT=$HOME/.virtualenvs/ghpages/bin/ghp-import
  MESSAGE=$(git log -1 HEAD --pretty=format:%s)

  git stash --keep-index -q
  $PELICAN ./content -o "$TEMP_DIR" -s ./publishconf.py

  git checkout static
  git merge origin/static
  unset GIT_INDEX_FILE
  GIT_WORK_TREE="$TEMP_DIR" git add -A
  GIT_WORK_TREE="$TEMP_DIR" git ls-files --deleted -z | xargs -0rt rm
  GIT_WORK_TREE="$TEMP_DIR" git commit --allow-empty -m "Generated HTML: $MESSAGE"
  git checkout -- .
  git checkout master
  if [ "$(git stash list -n 1 | wc -l)" == "1" ]; then
    git stash pop -q
  fi
fi
